import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2, Download, RefreshCw } from "lucide-react";
import { showSuccess, showError } from "@/utils/toast";

interface Question {
  id: number;
  question: string;
  options?: string[];
  answer: string;
  explanation?: string;
}

interface GeneratorForm {
  topic: string;
  difficulty: string;
  questionType: string;
}

export default function QuestionGenerator() {
  const [form, setForm] = useState<GeneratorForm>({
    topic: "",
    difficulty: "medium",
    questionType: "multiple-choice",
  });
  const [questions, setQuestions] = useState<Question[]>([]);
  const [isGenerating, setIsGenerating] = useState(false);

  // Mock AI question generation
  const generateQuestions = async () => {
    if (!form.topic.trim()) {
      showError("Please enter a topic");
      return;
    }

    setIsGenerating(true);
    
    // Simulate API call delay
    await new Promise(resolve => setTimeout(resolve, 2000));

    // Mock generated questions based on topic and settings
    const mockQuestions: Question[] = [
      {
        id: 1,
        question: `What is the primary concept related to ${form.topic}?`,
        options: form.questionType === "multiple-choice" ? ["Option A", "Option B", "Option C", "Option D"] : undefined,
        answer: "The correct answer would be generated by AI",
        explanation: "This explanation would be generated by AI based on the topic."
      },
      {
        id: 2,
        question: `Explain the key principles of ${form.topic}.`,
        options: form.questionType === "multiple-choice" ? ["Principle 1", "Principle 2", "Principle 3", "Principle 4"] : undefined,
        answer: "A detailed explanation would be provided here.",
        explanation: "This would contain the AI-generated explanation."
      },
      {
        id: 3,
        question: `How does ${form.topic} impact its related field?`,
        options: form.questionType === "multiple-choice" ? ["Impact A", "Impact B", "Impact C", "Impact D"] : undefined,
        answer: "The impact analysis would be generated here.",
        explanation: "AI-generated impact explanation."
      },
      {
        id: 4,
        question: `What are the common misconceptions about ${form.topic}?`,
        options: form.questionType === "multiple-choice" ? ["Misconception 1", "Misconception 2", "Misconception 3", "Misconception 4"] : undefined,
        answer: "Common misconceptions would be listed here.",
        explanation: "AI-generated clarification of misconceptions."
      },
      {
        id: 5,
        question: `Compare and contrast different aspects of ${form.topic}.`,
        options: form.questionType === "multiple-choice" ? ["Comparison A", "Comparison B", "Comparison C", "Comparison D"] : undefined,
        answer: "A comprehensive comparison would be provided.",
        explanation: "AI-generated comparative analysis."
      },
      {
        id: 6,
        question: `What are the practical applications of ${form.topic}?`,
        options: form.questionType === "multiple-choice" ? ["Application 1", "Application 2", "Application 3", "Application 4"] : undefined,
        answer: "Real-world applications would be described here.",
        explanation: "AI-generated application examples."
      },
      {
        id: 7,
        question: `Describe the historical development of ${form.topic}.`,
        options: form.questionType === "multiple-choice" ? ["Period A", "Period B", "Period C", "Period D"] : undefined,
        answer: "Historical context would be provided here.",
        explanation: "AI-generated historical overview."
      },
      {
        id: 8,
        question: `What are the future trends in ${form.topic}?`,
        options: form.questionType === "multiple-choice" ? ["Trend 1", "Trend 2", "Trend 3", "Trend 4"] : undefined,
        answer: "Future trends would be analyzed here.",
        explanation: "AI-generated future predictions."
      },
      {
        id: 9,
        question: `How can ${form.topic} be optimized or improved?`,
        options: form.questionType === "multiple-choice" ? ["Method 1", "Method 2", "Method 3", "Method 4"] : undefined,
        answer: "Optimization strategies would be outlined here.",
        explanation: "AI-generated improvement suggestions."
      },
      {
        id: 10,
        question: `Summarize the most important aspects of ${form.topic}.`,
        options: form.questionType === "multiple-choice" ? ["Summary A", "Summary B", "Summary C", "Summary D"] : undefined,
        answer: "A comprehensive summary would be provided.",
        explanation: "AI-generated summary of key points."
      }
    ];

    setQuestions(mockQuestions);
    setIsGenerating(false);
    showSuccess("Questions generated successfully!");
  };

  const downloadQuestions = () => {
    if (questions.length === 0) {
      showError("No questions to download");
      return;
    }

    let content = `AI Generated Exam Questions\n`;
    content += `Topic: ${form.topic}\n`;
    content += `Difficulty: ${form.difficulty}\n`;
    content += `Question Type: ${form.questionType}\n`;
    content += `Generated on: ${new Date().toLocaleDateString()}\n\n`;
    content += "=".repeat(50) + "\n\n";

    questions.forEach((q, index) => {
      content += `Question ${index + 1}: ${q.question}\n\n`;
      if (q.options) {
        q.options.forEach((option, optIndex) => {
          content += `${String.fromCharCode(65 + optIndex)}) ${option}\n`;
        });
        content += "\n";
      }
      content += `Answer: ${q.answer}\n`;
      if (q.explanation) {
        content += `Explanation: ${q.explanation}\n`;
      }
      content += "\n" + "-".repeat(30) + "\n\n";
    });

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `exam-questions-${form.topic.toLowerCase().replace(/\s+/g, "-")}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    showSuccess("Questions downloaded successfully!");
  };

  const regenerateQuestions = () => {
    generateQuestions();
  };

  return (
    <div className="space-y-8">
      {/* Input Form */}
      <Card className="border-blue-200 shadow-lg">
        <CardHeader>
          <CardTitle className="text-2xl text-blue-900">Generate Exam Questions</CardTitle>
          <CardDescription className="text-blue-700">
            Enter any topic and let AI create comprehensive exam questions for you
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-6">
          <div className="space-y-2">
            <Label htmlFor="topic" className="text-blue-900 font-medium">
              Topic or Subject
            </Label>
            <Input
              id="topic"
              placeholder="e.g., Photosynthesis, Python Loops, World War II"
              value={form.topic}
              onChange={(e) => setForm({ ...form, topic: e.target.value })}
              className="border-blue-200 focus:border-blue-500 focus:ring-blue-500"
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="space-y-2">
              <Label htmlFor="difficulty" className="text-blue-900 font-medium">
                Difficulty Level
              </Label>
              <Select
                value={form.difficulty}
                onValueChange={(value) => setForm({ ...form, difficulty: value })}
              >
                <SelectTrigger id="difficulty" className="border-blue-200">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="easy">Easy</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="hard">Hard</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="questionType" className="text-blue-900 font-medium">
                Question Type
              </Label>
              <Select
                value={form.questionType}
                onValueChange={(value) => setForm({ ...form, questionType: value })}
              >
                <SelectTrigger id="questionType" className="border-blue-200">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="multiple-choice">Multiple Choice</SelectItem>
                  <SelectItem value="short-answer">Short Answer</SelectItem>
                  <SelectItem value="true-false">True/False</SelectItem>
                  <SelectItem value="mixed">Mixed</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <Button
            onClick={generateQuestions}
            disabled={isGenerating}
            className="w-full bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 text-white font-medium py-3"
          >
            {isGenerating ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Generating Questions...
              </>
            ) : (
              "Generate Questions"
            )}
          </Button>
        </CardContent>
      </Card>

      {/* Generated Questions */}
      {questions.length > 0 && (
        <Card className="border-blue-200 shadow-lg">
          <CardHeader className="flex flex-row items-center justify-between">
            <div>
              <CardTitle className="text-xl text-blue-900">
                Generated Questions ({questions.length})
              </CardTitle>
              <CardDescription className="text-blue-700">
                Topic: {form.topic} | Difficulty: {form.difficulty} | Type: {form.questionType}
              </CardDescription>
            </div>
            <div className="flex gap-2">
              <Button
                onClick={regenerateQuestions}
                variant="outline"
                className="border-blue-200 text-blue-600 hover:bg-blue-50"
              >
                <RefreshCw className="mr-2 h-4 w-4" />
                Regenerate
              </Button>
              <Button
                onClick={downloadQuestions}
                variant="outline"
                className="border-blue-200 text-blue-600 hover:bg-blue-50"
              >
                <Download className="mr-2 h-4 w-4" />
                Download
              </Button>
            </div>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
              {questions.map((question, index) => (
                <div key={question.id} className="border border-blue-100 rounded-lg p-4 bg-blue-50">
                  <h3 className="font-semibold text-blue-900 mb-3">
                    Question {index + 1}: {question.question}
                  </h3>
                  
                  {question.options && (
                    <div className="ml-4 mb-3 space-y-2">
                      {question.options.map((option, optIndex) => (
                        <div key={optIndex} className="text-gray-700">
                          {String.fromCharCode(65 + optIndex)}) {option}
                        </div>
                      ))}
                    </div>
                  )}

                  <div className="ml-4 space-y-2">
                    <div className="text-green-700 font-medium">
                      <strong>Answer:</strong> {question.answer}
                    </div>
                    {question.explanation && (
                      <div className="text-gray-600 text-sm">
                        <strong>Explanation:</strong> {question.explanation}
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}